server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Rediriger toutes les routes vers index.html (Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
