apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projetjee
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/VOTRE_USERNAME/VOTRE_REPO.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: projetjee

  syncPolicy:
    automated:
      prune: true       # supprime les ressources retirées du repo
      selfHeal: true    # re-synchronise si quelqu'un modifie manuellement
    syncOptions:
      - CreateNamespace=true
