apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: projetjee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: image: safebouzidi199/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/projetjee
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: projetjee
spec:
  selector:
    app: backend
  ports:
    - port: 8080
