FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY ../backend/.mvn .mvn
COPY ../backend/mvnw .
COPY ../backend/pom.xml .
RUN ./mvnw dependency:go-offline -q
COPY ../backend/src src
RUN ./mvnw package -DskipTests -q

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/ProjetJee-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
