FROM node:22-alpine AS build
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build

FROM nginx:latest
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
