name: CI-CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    # ===== BACKEND =====
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Backend
      run: |
        cd backend
        mvn clean install -DskipTests

    # ===== FRONTEND =====
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    # ===== DOCKER =====
    - name: Build Docker images
      run: |
        docker build -t backend ./ -f docker/Dockerfile.backend
        docker build -t frontend ./ -f docker/Dockerfile.frontend
